import 'dart:math';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../data/models/customer_model.dart';
import '../../../../providers/app_providers.dart';
import '../../../widgets/common/common_widgets.dart';

class AddCustomerDialog extends StatefulWidget {
  const AddCustomerDialog({super.key});

  @override
  State<AddCustomerDialog> createState() => _AddCustomerDialogState();
}

class _AddCustomerDialogState extends State<AddCustomerDialog> {
  final _formKey = GlobalKey<FormState>();
  final _companyController = TextEditingController();
  final _contactController = TextEditingController();
  final _phoneController = TextEditingController();
  final _emailController = TextEditingController();
  final _addressController = TextEditingController();
  double _creditScore = 100.0;
  bool _isLoading = false;

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final code = 'CUST-${Random().nextInt(90000000) + 10000000}';
      
      final customer = CustomerModel(
        id: '', // Generated by Firestore
        customerCode: code,
        companyName: _companyController.text.trim(),
        contactPerson: _contactController.text.trim(),
        phoneNumber: _phoneController.text.trim(),
        email: _emailController.text.trim(),
        businessRegistrationNo: '', // Deprecated per user request
        address: _addressController.text.trim(),
        creditLimit: 0, // Deprecated per user request
        creditTerm: 'COD', // Deprecated per user request
        status: 'Active',
        outstandingBalance: 0,
        creditScore: _creditScore,
      );

      await context.read<CustomerProvider>().addCustomer(customer);

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Customer added successfully!'), backgroundColor: AppColors.success),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to add customer: $e'), backgroundColor: AppColors.danger),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  void dispose() {
    _companyController.dispose();
    _contactController.dispose();
    _phoneController.dispose();
    _emailController.dispose();
    _addressController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add New Customer', style: TextStyle(fontWeight: FontWeight.w800, color: AppColors.primary)),
      content: SizedBox(
        width: 500,
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                _buildField('Company Name', _companyController, true),
                _buildField('Contact Person', _contactController, true),
                Row(
                  children: [
                    Expanded(child: _buildField('Phone Number', _phoneController, true)),
                    const SizedBox(width: 16),
                    Expanded(child: _buildField('Email Address', _emailController, false)),
                  ],
                ),
                _buildField('Full Address', _addressController, true, maxLines: 3),
                const SizedBox(height: 12),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text('Initial Credit Score', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 13, color: AppColors.textSecondary)),
                        Text('${_creditScore.toInt()}%', style: const TextStyle(fontWeight: FontWeight.w800, color: AppColors.primary)),
                      ],
                    ),
                    Slider(
                      value: _creditScore,
                      min: 0,
                      max: 100,
                      divisions: 100,
                      activeColor: AppColors.primary,
                      onChanged: (val) => setState(() => _creditScore = val),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel', style: TextStyle(color: AppColors.textSecondary)),
        ),
        AppButton(
          label: 'Save Customer',
          icon: Icons.check_circle_rounded,
          isLoading: _isLoading,
          onPressed: _submit,
        ),
      ],
    );
  }

  Widget _buildField(String label, TextEditingController controller, bool required, {int maxLines = 1}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 13, color: AppColors.textSecondary)),
          const SizedBox(height: 6),
          TextFormField(
            controller: controller,
            maxLines: maxLines,
            decoration: InputDecoration(
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
              enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: const BorderSide(color: AppColors.border)),
              contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            ),
            validator: (val) {
              if (required && (val == null || val.trim().isEmpty)) {
                return 'This field is required';
              }
              return null;
            },
          ),
        ],
      ),
    );
  }
}
